on:
  push:
    tags:
      - 'sdk-py-v*'
  workflow_dispatch:

name: Publish Python to pypi

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: seaplane-sdk/python
    strategy:
      matrix:
        python-version: ['3.9']
        poetry-version: ['1.1.13']
    steps:
      - uses: actions/checkout@v3      
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build